# -*- coding: utf-8 -*-
"""nlp_models_sudu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tASlr5-QQD66GwhcARrK_EE48piEv7z0
"""

import nltk, re, string, math

nltk.download("punkt")
nltk.download("punkt_tab")

from nltk.tokenize import word_tokenize
from nltk.util import ngrams
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt

"""Corpus and Normalization"""

corpus = """Natural language processing is a subfield of linguistics computer science
and artificial intelligence it enables computers to understand human language
processing text is important machine learning helps in natural language understanding
deep learning models are used for text classification and language generation tasks
the field has grown rapidly with the advent of transformer based models such as bert
and gpt these models have achieved state of the art results on many benchmarks"""

def normalize(text):
  text = text.lower()
  text = re.sub(r'\d+','',text)
  text = re.sub(r'\s+',' ',text).strip()
  text = text.translate(str.maketrans('','',string.punctuation))
  return text

normalized = normalize(corpus)
tokens = word_tokenize(normalized)

# print(normalized)
# print(tokens)

"""NGRAMS + WORDCLOUD"""

unigrams = Counter(ngrams(tokens, 1))
bigrams  = Counter(ngrams(tokens, 2))
trigrams = Counter(ngrams(tokens, 3))

print("Top 5 Unigrams:", unigrams.most_common(5))
print("Top 5 Bigrams:",  bigrams.most_common(5))
print("Top 5 Trigrams:", trigrams.most_common(5))

def plot_wordcloud(freq, title):
    words = {' '.join(k): v for k, v in freq.items()}
    wc = WordCloud().generate_from_frequencies(words)
    plt.imshow(wc)
    plt.title(title)
    plt.axis('off')
    plt.show()

plot_wordcloud(unigrams, "Unigram")
plot_wordcloud(bigrams,  "Bigram")
plot_wordcloud(trigrams, "Trigram")

"""Perplexity"""

print("\n=== EXP 2: PERPLEXITY ===")

split = int(len(tokens) * 0.8)
train_tokens = tokens[:split]
test_tokens  = tokens[split:]

train_unigrams = Counter(ngrams(train_tokens, 1))
train_bigrams  = Counter(ngrams(train_tokens, 2))
train_trigrams = Counter(ngrams(train_tokens, 3))
vocab_size = len(set(train_tokens))

def unigram_prob(w):
    return (train_unigrams[w] + 1) / (len(train_tokens) + vocab_size)

def bigram_prob(w1, w2):
    return (train_bigrams[(w1, w2)] + 1) / (train_unigrams[w1] + vocab_size)

def trigram_prob(w1, w2, w3):
    return (train_trigrams[(w1, w2, w3)] + 1) / (train_bigrams[(w1, w2)] + vocab_size)

def perplexity(probs):
    N = len(probs)
    return 2 ** (-sum(math.log2(p) for p in probs) / N)

uni_probs = [unigram_prob(w) for w in test_tokens]
bi_probs  = [bigram_prob(test_tokens[i-1], test_tokens[i]) for i in range(1, len(test_tokens))]
tri_probs = [trigram_prob(test_tokens[i-2], test_tokens[i-1], test_tokens[i]) for i in range(2, len(test_tokens))]

print("Unigram  Perplexity:", perplexity(uni_probs))
print("Bigram   Perplexity:", perplexity(bi_probs))
print("Trigram  Perplexity:", perplexity(tri_probs))

"""Stemming"""

from nltk.stem import PorterStemmer, SnowballStemmer, LancasterStemmer
import pandas as pd

porter = PorterStemmer()
snowball = SnowballStemmer('english')
lancaster = LancasterStemmer()

df_stem = pd.DataFrame({
    "Word": tokens[:20],
    "Porter" : [porter.stem(w) for w in tokens[:20]],
    'Snowball' : [snowball.stem(w) for w in tokens[:20]],
    'Lancaster' : [lancaster.stem(w) for w in tokens[:20]]
})

print(df_stem.to_string(index=False))

#vocab reduction
stemmed_tokens = [porter.stem(w) for w in tokens]
print("Before stemming",len(set(tokens)))
print("After stemming",len(set(stemmed_tokens)))

"""POS Tagging

"""

from nltk import pos_tag
nltk.download("averaged_perceptron_tagger")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("treebank")
text = "The quick brown fox is jumping over the lazy dog"
tokens = word_tokenize(text)

tags = pos_tag(tokens)
print(tags)

"""TF - IDF

"""

from sklearn.feature_extraction.text import TfidfVectorizer

docs = corpus.split('\n')

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(docs)

feature_names = vectorizer.get_feature_names_out()
print("Vocabulary: ", feature_names)

df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns = feature_names,
    index = [f"Doc{i+1}" for i in range(len(docs))]
)

print(df.round(3).to_string())

"""SOTa models

"""

from transformers import pipeline

docs = corpus.split('\n')

bert = pipeline("fill-mask", model="bert-base-uncased")

sentence = docs[0]
masked = sentence.replace("processing","[MASK]")

print("\nBert")
for r in bert(masked):
  print(r['token_str'],"->",round(r['score'],4))

gpt = pipeline("text-generation",model="gpt2")

print("\nGPT2")
print(gpt(docs[0],max_length=40)[0]["generated_text"])

roberta = pipeline("fill-mask",model="roberta-base")

sentence = docs[1]
masked = sentence.replace("language","<mask>")

print("\nRoberta")
for r in roberta(masked):
  print(r['token_str'],"->",round(r['score'],4))

sentiment = pipeline("sentiment-analysis")
results = sentiment(docs)

for doc,res in zip(docs,results):
    print(doc)
    print(res)
    print()

"""Simple RNN"""

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

#corpus

tokenizer = Tokenizer()
tokenizer.fit_on_texts([corpus])
sequence = tokenizer.texts_to_sequences([corpus])[0]

X,y = [],[]
for i in range(1,len(sequence)):
  X.append(sequence[:i])
  y.append(sequence[i])

X = pad_sequences(X)
y = np.array(y)

model = Sequential([
    Embedding(input_dim=100,output_dim=10,input_length=X.shape[1]),
    SimpleRNN(10),
    Dense(100,activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')
model.fit(X,y,epochs=50,verbose=0)

test_text = "natural language"
test_seq = tokenizer.texts_to_sequences([test_text])
test_seq = pad_sequences(test_seq, maxlen=X.shape[1])

prediction = model.predict(test_seq)
predicted_word = tokenizer.index_word[np.argmax(prediction)]

print("Next word: ",predicted_word)

"""LSTM

"""

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

#corpus
docs = corpus.split('\n')
labels = [1,0,1,0,1,0]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
X = tokenizer.texts_to_sequences(docs)
X = pad_sequences(X)
y = np.array(labels)

model = Sequential([
    Embedding(input_dim=100,output_dim=10,input_length=X.shape[1]),
    LSTM(10),
    Dense(1,activation='sigmoid')
])

model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(X,y,epochs=20,verbose=0)

test_text = "market is strong"
test_seq = tokenizer.texts_to_sequences([test_text])
test_seq = pad_sequences(test_seq,maxlen=X.shape[1])

prediction = model.predict(test_seq)
sentiment = "Positive" if prediction > 0.5 else "Negative"

print("Sentiment: ", sentiment)