# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IMWSJ-LYS7mnghxXJVFMinPTe4AWXTb
"""

import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.util import ngrams
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

with open('corpus.txt','r') as f:
  corpus=f.read()

print(corpus)

def preprocess(text):
  text=text.lower()
  text=text.translate(str.maketrans('','',string.punctuation))
  tokens=word_tokenize(text)
  stop_words=set(stopwords.words('english'))
  tokens=[w for w in tokens if w not in stop_words]
  tokens = [w for w in tokens if w.isalpha()]

  return tokens

tokens=preprocess(corpus)

print(tokens)

unigrams=tokens
bigrams=list(ngrams(tokens,2))
trigrams=list(ngrams(tokens,3))

print(unigrams)
print(bigrams)
print(trigrams)

print(Counter(unigrams))
print(Counter(bigrams))
print(Counter(trigrams))

wc1=WordCloud(background_color='white').generate(" ".join(unigrams))
plt.imshow(wc1)

bi_words=(" ".join(b) for b in bigrams)
wc2=WordCloud(background_color='white').generate(" ".join(bi_words))
plt.imshow(wc2)

#Exercise 2

import math

splits=int(0.8*len(tokens))
train=tokens[:splits]
test=tokens[splits:]

train=["<s>"]+train+["</s>"]
test=["<s>"]+test+["</s>"]

uni=Counter(train)
bi=Counter(ngrams(train,2))
tri=Counter(ngrams(train,3))

V=len(uni)
N=sum(uni.values())

def unigram_prob(w):
  return (uni[w]+1)/(N+V)

def bigram_prob(w1,w2):
  return(bi[(w1,w2)]+1)/(uni[w1]+V)

def trigram_prob(w1,w2,w3):
  return (tri[(w1,w2,w3)]+1)/(bi[(w1,w2)]+V)

def perplexity(test,n):
  p=1
  N=len(test)

  if n==1:
    for w in test:
      p*=unigram_prob(w)

  elif n==2:
    for w1,w2 in ngrams(test,2):
      p*=bigram_prob(w1,w2)

  elif n==3:
    for w1,w2,w3 in ngrams(test,3):
      p*=trigram_prob(w1,w2,w3)

  return pow(p,-1/N)

print("Unigram Perplexity:", perplexity(test, 1))
print("Bigram Perplexity:", perplexity(test, 2))
print("Trigram Perplexity:", perplexity(test, 3))

from transformers import pipeline

bert = pipeline("fill-mask", model="bert-base-uncased")

# try masking each word
words = corpus.split()
importance = {}

for i in range(len(words)):
    temp = words.copy()
    temp[i] = "[MASK]"
    masked = " ".join(temp)

    result = bert(masked)[0]  # top prediction
    importance[words[i]] = result['score']

print("Word Importance:", importance)

sorted_words = sorted(importance.items(), key=lambda x: x[1], reverse=True)

top = sorted_words[:10]

print("Top Important Words:")
for w, s in top:
    print(w, round(s, 3))

from transformers import pipeline

# -------- BERT --------
bert = pipeline("fill-mask", model="bert-base-uncased")
print("BERT:", bert("NLP is [MASK] and powerful."))

# -------- RoBERTa --------
roberta = pipeline("fill-mask", model="roberta-base")
print("\nRoBERTa:", roberta("Transformers are <mask> models."))

# -------- GPT --------
gpt = pipeline("text-generation", model="gpt2")
print("\nGPT:", gpt("Artificial Intelligence will", max_new_tokens=20))

!pip install stemming
from nltk.stem import PorterStemmer, SnowballStemmer, LancasterStemmer
from stemming.lovins import stem as lovins_stem

porter = PorterStemmer()
snowball = SnowballStemmer("english")
lancaster = LancasterStemmer()

# ------------------ OUTPUT ------------------
print("Word\tPorter\tSnowball\tLancaster\tLovins\n")

for w in tokens:
    print(w, "\t",
          porter.stem(w), "\t",
          snowball.stem(w), "\t",
          lancaster.stem(w), "\t",
          lovins_stem(w))

import pandas as pd

data = []

for w in tokens:
    data.append([
        w,
        porter.stem(w),
        snowball.stem(w),
        lancaster.stem(w),
        lovins_stem(w)

    ])

df = pd.DataFrame(data, columns=["Word", "Porter", "Snowball", "Lancaster","Lovins"])
print(df)

docs = [
    "He is running and runs every day",
    "She was running faster than others",
    "They have run in many competitions",
    "The runner is running in a race",
    "Running and runs are forms of run"
]

all_words=[]

for doc in docs:
  all_words.extend(word_tokenize(doc.lower()))

print(len(set(all_words)))
bfr=len(set(all_words))

stemmed_words=[]
for w in all_words:
  stemmed_words.append(porter.stem(w))

print(len(set(stemmed_words)))
after=len(set(stemmed_words))
red=bfr-after
perc=(red/bfr)*100
print(perc)

#exercise 5
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import UnigramTagger,BrillTaggerTrainer
from nltk.tag.brill import brill24
from nltk.corpus import treebank

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('treebank')

text = "The quick brown fox is jumping over the lazy dog"
text=text.lower()

words=word_tokenize(text)

def rule_based_tagger(words):
  tags=[]
  for w in words:
    if w in ['the','a','an']:
      tag='DT'
    elif w in ['in','on','over','under']:
      tag='IN'
    elif w.endswith("ing"):
      tag='VBG'
    elif w.endswith("ed"):
      tag='VBD'
    elif w.endswith('ly'):
      tag='RB'
    elif w.endswith(('ous','able','ful','ive')):
      tag='JJ'
    elif w[0].isupper():
      tag='NNP'
    else:
      tag='NN'

    tags.append((w,tag))
  return tags

print(rule_based_tagger(words))

tags=nltk.pos_tag(words)
print(tags)

train_data=treebank.tagged_sents()[:200]

unigram=UnigramTagger(train_data)
trainer=BrillTaggerTrainer(unigram,brill24())
brill_tagger=trainer.train(train_data)
brill_tag=brill_tagger.tag(words)
print(brill_tag)

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import treebank
from nltk.tag import hmm

nltk.download('punkt')
nltk.download('treebank')

# ------------------ TRAIN DATA ------------------
train_data = treebank.tagged_sents()[:300]

# ------------------ TRAIN HMM ------------------
trainer = hmm.HiddenMarkovModelTrainer()
hmm_tagger = trainer.train_supervised(train_data)

# ------------------ INPUT ------------------
text = "Financial markets show strong growth and economic stability."
words = word_tokenize(text)

# ------------------ TAGGING ------------------
tags = hmm_tagger.tag(words)

print("HMM POS Tags:")
print(tags)

important = [
    w for w, t in tags
    if t.startswith('NN') or t.startswith('JJ')
]
from collections import Counter

freq = Counter(important)
top = freq.most_common(10)

print(top)

import pandas as pd

df = pd.DataFrame(top, columns=["Word", "Frequency"])
print(df)

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# ------------------ CORPUS ------------------
text = """Natural language processing is fun.
Machine learning improves NLP.
Deep learning helps in understanding language."""

# ------------------ TOKENIZE ------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
seq = tokenizer.texts_to_sequences([text])[0]

# ------------------ CREATE SEQUENCES ------------------
X, y = [], []

for i in range(1, len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

# ------------------ PAD ------------------
X = pad_sequences(X)
y = np.array(y)

# ------------------ MODEL ------------------
model = Sequential([
    Embedding(100, 10, input_length=X.shape[1]),
    SimpleRNN(10),
    Dense(100, activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
model.fit(X, y, epochs=50, verbose=0)

# ------------------ PREDICT ------------------
test = "natural language"
test_seq = tokenizer.texts_to_sequences([test])
test_seq = pad_sequences(test_seq, maxlen=X.shape[1])

pred = model.predict(test_seq)
print("Next word:", tokenizer.index_word[np.argmax(pred)])

from tensorflow.keras.layers import LSTM

# ------------------ DATA ------------------
texts = [
    "market is growing rapidly",
    "economy is weak and unstable",
    "profits are increasing",
    "losses are high"
]

labels = [1, 0, 1, 0]

# ------------------ TOKENIZE ------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

X = tokenizer.texts_to_sequences(texts)
X = pad_sequences(X)
y = np.array(labels)

# ------------------ MODEL ------------------
model = Sequential([
    Embedding(100, 10, input_length=X.shape[1]),
    LSTM(10),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=50, verbose=0)

# ------------------ TEST ------------------
test = tokenizer.texts_to_sequences(["market is strong"])
test = pad_sequences(test, maxlen=X.shape[1])

pred = model.predict(test)
print("Sentiment:", "Positive" if pred > 0.5 else "Negative")

from nltk.tokenize import sent_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

docs = sent_tokenize(corpus)

print("Number of documents:", len(docs))

# ------------------ TF-IDF ------------------
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(docs)

# ------------------ FEATURES ------------------
features = vectorizer.get_feature_names_out()

# ------------------ IMPORTANCE ------------------
scores = np.sum(tfidf_matrix.toarray(), axis=0)

# ------------------ TOP WORDS ------------------
top_indices = scores.argsort()[-10:][::-1]

top_words = [(features[i], scores[i]) for i in top_indices]

print("\nTop Important Words:")
for w, s in top_words:
    print(w, round(s, 3))

# ------------------ TABLE ------------------
df = pd.DataFrame(top_words, columns=["Word", "Importance"])
print("\nTable:\n", df)