# -*- coding: utf-8 -*-
"""NLP_MODELS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExTNMXXtkONc90dxFj0IOmHw_LmzJ3sk

IMPORTS AND DOWNLOADS
"""

import nltk , string, re , math , pandas as pd, numpy as np, random


from nltk.util import ngrams
from nltk.stem import PorterStemmer,LancasterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.corpus import treebank , stopwords
from collections import Counter
from nltk import pos_tag
from nltk.tag import BrillTaggerTrainer
from nltk.tag.brill import brill24

from sklearn.feature_extraction.text import TfidfVectorizer

!pip install stemming
from stemming.lovins import stem as lovins_stem

from wordcloud import WordCloud
import matplotlib.pyplot as plt

from transformers import pipeline

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('brill')
nltk.download('treebank')

"""TEXT PREROCESSING"""

def preprocess(corpus):
  text = corpus.lower()
  text = text.translate(str.maketrans('','',string.punctuation))
  tokens = word_tokenize(text)
  stop_words = set(stopwords.words('english'))
  tokens = [word for word in tokens
            if word not in stop_words and word.isalpha() ]
  return tokens

corpus = """
Natural Language Processing is a subfield of artificial intelligence that focuses on
the interaction between computers and humans using natural language. It enables machines to understand, interpret, and generate human language in a meaningful way. NLP techniques are widely used in applications such as sentiment analysis, machine translation, chatbots, information retrieval, speech recognition, and text summarization. Stemming plays a vital
role in reducing words to their root form, improving search accuracy and reducing vocabulary
size in text processing systems."""

tokens = preprocess(corpus)
split = int(0.8 * len(tokens))
train_set = tokens[:split]
test_set = tokens[split:]

"""Ngrams and wordcloud

"""

unigrams = list(ngrams(train_set,1))
bigrams = list(ngrams(train_set,2))
trigrams = list(ngrams(train_set,3))

print("Top 5 Unigrams:",Counter(unigrams).most_common(5))
print("Top 5 Bigrams:",  Counter(bigrams).most_common(5))
print("Top 5 Trigrams:", Counter(trigrams).most_common(5))

unif = Counter(unigrams)
bif = Counter(bigrams)
trif = Counter(trigrams)
def wc(ngram,title):
  words=[''.join(n) for n in ngram]
  fwords = Counter(words)
  wrc = WordCloud(width=900,height=600,background_color='white').generate_from_frequencies(fwords)
  plt.imshow(wrc)
  plt.axis('off')
  plt.title(title)
  plt.show()

wc(unigrams,"unigram")
wc(bigrams,"bigram")
wc(trigrams,"trigram")

"""Perplexity"""

unifreq = FreqDist(unigrams)
bifreq = FreqDist(bigrams)
trifreq = FreqDist(trigrams)
vocab_size = len(unifreq)
def uniprb(word):
  return (unifreq[(word,)]+1)/(len(train_set)+vocab_size)
def biprb(word):
  return (bifreq[word]+1) / (unifreq[(word[0],)]+vocab_size)
def triprb(word):
  return (trifreq[word]+1)/ (bifreq[word[:2]]+vocab_size)
def perplexity(test_set,n):
  logprb = 0
  N = 0
  testngrams = list(ngrams(test_set,n))
  for tg in testngrams:
     if n == 1:
       prb = uniprb(tg[0])
     elif n == 2:
       prb = biprb(tg)
     else:
       prb = triprb(tg)
     logprb += math.log(prb)
     N += 1
     return math.exp(-logprb/N)

unigram_perplexity = perplexity(test_set, 1)
bigram_perplexity = perplexity(test_set, 2)
trigram_perplexity = perplexity(test_set, 3)

print("Model Evaluation using Perplexity")
print("---------------------------------")
print(f"Unigram Perplexity : {unigram_perplexity:.4f}")
print(f"Bigram Perplexity : {bigram_perplexity:.4f}")
print(f"Trigram Perplexity : {trigram_perplexity:.4f}")

"""Stemmer"""

porter = PorterStemmer()
snowball = SnowballStemmer("english")
lancaster = LancasterStemmer()
print("---------------------------Stemming Results---------------------------")
print(f"{'Word':<15}{'Porter':<15}{'Snowball':<15}{'Lancaster':<15}{'Lovins'}")
stem_data =[]
for word in tokens:
  p=porter.stem(word)
  s=snowball.stem(word)
  l=lancaster.stem(word)
  lo=lovins_stem(word)
  stem_data.append((word, p, s, l, lo))
  print(f"{word:<15}{p:<15}{s:<15}{l:<15}{lo}")

stems_data = [porter.stem(w) for w in tokens]
print("\nBefore stemming vocab size:", len(set(tokens)))
print("After stemming  vocab size:", len(set(stems_data)))

"""Pos Tagging"""

from nltk.tag import UnigramTagger
sample = "The quick brown fox is jumping over the lazy dog"
sample_tokens = word_tokenize(sample)
print("Tokens:", sample_tokens)

def rulebasedtag(words):
  tags =[]
  for word in words:
    w = word.lower()
    if w in ['the','an','a']: tag='DT'
    elif w in ['in','on','at','over','under','with']: tag ='IN'
    elif w.endswith('ing'): tag = 'VBG'
    elif w.endswith('ed'): tag = 'VBD'
    elif w.endswith('ly'): tag = 'RB'
    elif w.endswith(('ful','ive','ous','able')): tag = 'JJ'
    elif word[0].isupper(): tag = 'NNP'
    else: tag = 'NN'
    tags.append((word,tag))
  return tags

rule_tags = rulebasedtag(sample_tokens)
print("\nRule-Based:", rule_tags)

pos_tags = nltk.pos_tag(sample_tokens)
print("\n HMM/Pos Stat tags",pos_tags)

train_data = treebank.tagged_sents()[:200]
unigram = UnigramTagger(train_data)
trainer = BrillTaggerTrainer(unigram, brill24())
brill_tagger = trainer.train(train_data)
brill_tags = brill_tagger.tag(sample_tokens)
print("\nBrill Tagger Output:")
print(brill_tags)

"""SoTA models

"""

tweets = [
"இjø இஇo d(இg(ø μ-இ/", "இjø இஇo aஇyD 8dwஇD", "இjø 6ilD gஇஇy μ-இ/",
"aw(øp6இஇஇ இwṅпwjμd-இஇ", "d(இg(ø røyD 6ilD",
"இjø ypy d(இg(ø пwøஇD", "இஇ&இ- dwjμD 8øஇa",
"இjø இi& d(இȧ μஇI- இ(இஇμ இwiJ&μ/",
"இjø இஇo аஇஇ-пwJ adwjμdwஇ rȧஇ/",
"ypyஇȧ இஇjø இ4ø/இஇஇ r4aw(ø&Pμஇ"
]

bert = pipeline("feature-extraction",model="bert-base-multilingual-cased")
for t in tweets:
  emb =bert(t)
  print("Tweet:", t)
  print("Vector length:",len(emb[0]),"\n")

roberta = pipeline("feature-extraction",model="roberta-base")
for t in tweets:
  emb =roberta(t)
  print("Tweet:", t)
  print("Vector length:",len(emb[0]),"\n")

gpt2= pipeline("text-generation",model="gpt2")
prompt = "The Government is "
out = gpt2(prompt,max_length=50)
print(out[0]["generated_text"])

t5 = pipeline("text-generation", model="t5-small")
for t in tweets:
    text = "classify sentiment: " + t
    out = t5(text)
    print(t, "->", out[0]["generated_text"])

print("\n=== EXP 3: SoTA LANGUAGE MODELS ===")

# BERT
bert = pipeline("fill-mask", model="bert-base-uncased")
print("BERT:")
for r in bert("Natural language [MASK] is a subfield of AI."):
    print(" ", r['token_str'], "→", round(r['score'], 4))

# GPT-2
gpt = pipeline("text-generation", model="gpt2")
print("\nGPT-2:")
print(" ", gpt("Natural language processing is", max_length=30, num_return_sequences=1)[0]['generated_text'])

# RoBERTa
roberta = pipeline("fill-mask", model="roberta-base")
print("\nRoBERTa:")
for r in roberta("Natural language <mask> is a subfield of AI."):
    print(" ", r['token_str'], "→", round(r['score'], 4))

"""TF IDF"""

# to read from a file:
#with open("sampletext.txt", "r", encoding="utf-8") as f:
# text = f.read()
doc = [" ".join(tokens)]

vectorizer = TfidfVectorizer(lowercase = True)
tfidfmatrix = vectorizer.fit_transform(doc)

feature_names = vectorizer.get_feature_names_out()
scores = tfidfmatrix.toarray()[0]

word_scores = list(zip(feature_names, scores))
sorted_words = sorted(word_scores, key=lambda x: x[1], reverse=True)

for word, score in sorted_words[:5]:
    print(word, score)

"""RNN and LSTM

"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np

texts = ["Spoken language is often different from written language."," 2000 HUB5 English is a dataset that's a transcription of 40 telephone conversations."," Signed language can also be annotated and transcribed to create a corpus."]
labels = [1,0,1]
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
seq = tokenizer.texts_to_sequences(texts)
x = pad_sequences(seq,maxlen=100)
x = np.array(x)
labels = np.array(labels)
model = Sequential([
    Embedding(5000,32),
    LSTM(64),
    Dense(1,activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,labels,epochs=5)
loss,acc = model.evaluate(x,labels)
print("Accuracy: ",acc)
print("Loss: ",loss)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

text = "NLP is an interesting subject"
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
tot_words = len(tokenizer.word_index)+1
in_seq = []
for i in range(1,len(text.split())):
    seq = text.split()[:i+1]
    encoded = tokenizer.texts_to_sequences([' ' .join(seq)])[0]
    in_seq.append(encoded)
max_len = max(len(x) for x in in_seq)
in_seq = pad_sequences(in_seq,maxlen=max_len,padding='pre')
x = in_seq[:,:-1]
y = in_seq[:,-1]
model = Sequential(
    [Embedding(tot_words,10,input_length=max_len-1),
     SimpleRNN(50),
     Dense(tot_words, activation='softmax')
    ])
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=100,verbose=0)

loss,acc = model.evaluate(x,y)
print("Accuracy: ",acc)
print("Loss: ",loss)

seed_text = "NLP is an interesting"
seq = tokenizer.texts_to_sequences([seed_text])[0]
seq = pad_sequences([seq],maxlen=max_len-1,padding='pre')
pred = np.argmax(model.predict(seq),axis=1)
for word,index in tokenizer.word_index.items():
    if index == pred:
        print("Next word: ",word)

import nltk
import numpy as np
import matplotlib.pyplot as plt
from nltk.tokenize import sent_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

nltk.download('punkt')

with open("sampletext.txt", "r", encoding="utf-8") as f:
    text = f.read()

texts = sent_tokenize(text)

labels = [1 if "good" in t.lower() else 0 for t in texts]

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(texts)
seq = tokenizer.texts_to_sequences(texts)

x = pad_sequences(seq, maxlen=100)
y = np.array(labels)

model = Sequential()
model.add(Embedding(5000, 32))
model.add(LSTM(64))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

if len(x) < 10:
    history = model.fit(x, y, epochs=5, validation_split=0.2)
else:
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
    history = model.fit(X_train, y_train, epochs=5)
    loss, acc = model.evaluate(X_test, y_test)
    print("Test Accuracy:", acc)
    print("Test Loss:", loss)

plt.plot(history.history['accuracy'])
if 'val_accuracy' in history.history:
    plt.plot(history.history['val_accuracy'])
plt.title("Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.show()

plt.plot(history.history['loss'])
if 'val_loss' in history.history:
    plt.plot(history.history['val_loss'])
plt.title("Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()

